spring:
  application:
    name: app-small-crm
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085

app:
  jwt:
    access:
      secretKey: ${APP_JWT_ACCESS_SECRET}
      expirationAt: 3000000
    refresh:
      secretKey: ${APP_JWT_REFRESH_SECRET}
      expirationAt: 9000000